ARG BASE_IMAGE_TAG=latest
FROM ghcr.io/attocash/work-server:${BASE_IMAGE_TAG}

LABEL org.opencontainers.image.source https://github.com/attocash/work-server

USER app

ENV SPRING_PROFILES_ACTIVE=cpu,json
