name: Pipeline

on:
  workflow_call:
  push:
    branches:
      - 'release/[0-9]+.x'
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yaml
  build:
    permissions:
      contents: read
      packages: write
    if: "startsWith(github.ref, 'refs/heads/')"
    needs:
      - test
    uses: ./.github/workflows/build.yaml
  build-rocm:
    permissions:
      packages: write
    if: "startsWith(github.ref, 'refs/heads/release/') && endsWith(github.ref, '.x')"
    needs:
      - build
    uses: ./.github/workflows/build-image.yaml
    with:
      image: rocm
  release-tag:
    permissions:
      contents: write
    if: "startsWith(github.ref, 'refs/heads/release/') && endsWith(github.ref, '.x')"
    needs:
      - build-rocm
    uses: ./.github/workflows/release-tag.yaml
    with:
      profile: rocm
  release-rocm:
    permissions:
      contents: write
    if: "startsWith(github.ref, 'refs/heads/release/') && endsWith(github.ref, '.x')"
    needs:
      - release
    uses: ./.github/workflows/release.yaml
    with:
      image: rocm
      next-tag: ${{ needs.release.outputs.next-tag }}
