name: Pipeline

on:
  push:
    branches:
      - 'release/[0-9]+.x'
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yaml
  build:
    permissions:
      contents: read
      packages: write
    needs:
      - test
    uses: ./.github/workflows/build.yaml
  build-rocm:
    permissions:
      packages: write
    needs:
      - build
    uses: ./.github/workflows/build-image.yaml
    with:
      image: rocm
  build-cuda:
    permissions:
      packages: write
    needs:
      - build
    uses: ./.github/workflows/build-image.yaml
    with:
      image: cuda
  release-tag:
    permissions:
      contents: write
    if: "startsWith(github.ref, 'refs/heads/release/') && endsWith(github.ref, '.x')"
    needs:
      - build-rocm
      - build-cuda
    uses: ./.github/workflows/release-tag.yaml
    with:
      profile: release
  release-rocm:
    permissions:
      packages: write
    needs:
      - release-tag
    uses: ./.github/workflows/release.yaml
    with:
      image: rocm
      next-tag: ${{ needs.release-tag.outputs.next-tag }}
  release-cuda:
    permissions:
      packages: write
    needs:
      - release-tag
    uses: ./.github/workflows/release.yaml
    with:
      image: cuda
      next-tag: ${{ needs.release-tag.outputs.next-tag }}
