# Managed by management-terraform

on:
  workflow_call:
    inputs:
      profile:
        required: true
        type: string
      bump-version:
        default: false
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.profile }}
    steps:
      - uses: jlumbroso/free-disk-space@main
        with:
          docker-images: true

      - uses: actions/checkout@v4

      - run: git fetch --tags

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: release
        run: |
          RELEASE_BRANCH=$(echo "${{ github.ref_name }}" | sed 's/release\///')
          MAJOR_VERSION=$(echo "$RELEASE_BRANCH" | awk -F. '{print $1}')
          LATEST_TAG=$(git tag --list "v$MAJOR_VERSION.*" --sort=-v:refname | head -n1)

          if [ -z "$LATEST_TAG" ]; then
            MINOR=0
          elif [ "${{ inputs.bump-version }}" == "true" ]; then
            MINOR=$(( ${LATEST_TAG##*.} + 1 ))
          else
            MINOR=${LATEST_TAG##*.}
          fi

          NEXT_TAG="$MAJOR_VERSION.$MINOR"

          docker build --build-arg BASE_IMAGE_TAG=${{ github.sha }} -t ghcr.io/${{ github.repository }}:${NEXT_TAG}-${{ inputs.profile }} -f Dockerfile.${{ inputs.profile }} .
          docker tag ghcr.io/${{ github.repository }}:${NEXT_TAG}-${{ inputs.profile }} ghcr.io/${{ github.repository }}:${MAJOR_VERSION}-${{ inputs.profile }}
          docker push ghcr.io/${{ github.repository }}:${NEXT_TAG}-${{ inputs.profile }}
          docker push ghcr.io/${{ github.repository }}:${MAJOR_VERSION}-${{ inputs.profile }}

          HIGHER_MAJOR_EXISTS=$(git tag --list 'v*' --sort=-v:refname | awk -F. '{print $1}' | sed 's/v//' | uniq | awk -v curr="$MAJOR_VERSION" '$1>curr {print "yes"; exit}')
          if [ "$HIGHER_MAJOR_EXISTS" != "yes" ]; then
            docker tag ghcr.io/${{ github.repository }}:${NEXT_TAG}-${{ inputs.profile }} ghcr.io/${{ github.repository }}:${{ inputs.profile }}
            docker push ghcr.io/${{ github.repository }}:${{ inputs.profile }}
          fi

          if [ "${{ inputs.bump-version }}" == "true" ]; then
            git tag v$NEXT_TAG
            git push origin v$NEXT_TAG
          fi
